#!/usr/bin/env ruby

#Place.create(name: "", address: "", description: "", user_id: 1)

Place.create(name: "Flamingo Fresh Food Bar", address: "Neustadtische Kirchstrasse 8 10117 Berlin", description: "Highly recommend this place for fresh tasty food. Good vibes and friendly staff! We had the gnocchi which was to die for, and the sandwich. Hands down favourite restaurant in Berlin!!", user_id: 1)
Place.create(name: "Yarok Fine Syrian Food from Damascus", address: "Torstr. 195 10115 Berlin", description: "This is a tiny sysrian bistro, they offer several meat and vegetarian dishes, also plates for two. The food is delicious, it tends to be full in the evenings.", user_id: 1)
Place.create(name: "Burgermeister", address: "Oberbaumstrasse 8 10997 Berlin", description: "Oberbaumstrasse 8, 10997 Berlin", user_id: 1)
Place.create(name: "Madami - Mom's Vietnamese Kitchen", address: "Rosa-Luxemburg-Str. 3 10178 Berlin", description: "Had a beautiful meal here. Amazing cocktails, excellent service and the best Vietnamese I've had outside of Vietnam. They have two restaurants, one round the corner which the waitress walked us to when they couldn't accommodate us in the main one. Shows how popular they are! Book if you plan to go...and you should!", user_id: 1)
Place.create(name: "Patta", address: "Krossener Str. 16, 10245 Berlin", description: "Up there with the best potato I've ever had, super tasty and one potato is enough too I not all eat a lot and it was very filling. Awesome place!", user_id: 1)
Place.create(name: "Mabuhay - Indonesian Restaurant", address: "Koethener Str. 28, 10963 Berlin", description: "If you want cheap and good food in an tiny place - this is the place to go! Indonesian at it's best, possibly. Try it out :, user_id: 1)", user_id: 1)
Place.create(name: "BBI - Berlin Burger International", address: "Pannierstr. 5, 12047 Berlin", description: "We where staying near by and just happened on this place. It was busy but worth the wait. The Burgers were so juicy. Loads of topping and the fires are tasty. Well worth a visit.", user_id: 1)
Place.create(name: "Mustafa's Gemuese Kebab", address: "Mehringdamm 32, 10961 Berlin, Germany", description: "Living in Germany you really have abundance of kebap joints to choose from. And believe me, I have visited a few... To quote my daughter \"you can't have a kebap anywhere else again\". That pretty much sums it up. Well worth queuing. Absolutely mouthwatering.", user_id: 1)
Place.create(name: "Scheers Schnitzel", address: "Warschauer Strasse Ecke Stralauer Allee, 10245 Berli", description: "A small place but a great schnitzel! No fancy overheads but the food is worth it! The boss is very friendly.", user_id: 1)
Place.create(name: "Curry61", address: "Oranienburger Str. 6, 10178 Berlin", description: "Really buzzing and busy. We ate at the stand outside for the full experience and had chips with mayo/ketchup, curry wurst and some other spicy sausage. All tasty. The curry sauce is very sweet but good nonetheless. Definitely a place to go while in Berlin.", user_id: 1)
Place.create(name: "Markthalle Neun Berlin Kreuzberg", address: "Eisenbahnstr. 42, 10997 Berlin", description: "Don't miss a visit to Market Halle 9 if you are in Berlin on a Thursday. We never had so much delicious food before.", user_id: 1)
Place.create(name: "Saigon - Green", address: "Kantstr. 23, 10623 Berlin", description: "Excellent pho soup. Everything we had was fresh. Friendly young staff with decent staff, attended a lot by locals for both dine in and take out.", user_id: 1)
Place.create(name: "Dada Falafel", address: "Linienstr. 132, 10115 Berlin, Germany", description: "Very nice vibe, the food is good, people are friendly. If you can then go on a Thursday night- that's when Orange Treeo plays live (Jazz band, user_id: 1) and they are amazing!", user_id: 1)
Place.create(name: "Burgeramt", address: "Krossener Str. 21-22, 10245 Berlin, Germany", description: "We went here twice during our week in Berlin as we enjoyed the fantastic burgers, hip decor and relaxed atmosphere so much! It looks good, tastes great and feels welcoming. Be prepared to wait for a table, even at 9pm on a Tuesday night in October, it's super- busy but the staff were really helpful and it's worth it.", user_id: 1)
Place.create(name: "Sadhu 2", address: "Weserstrasse 201, 12047 Berlin, Germany", description: "This is Very nice Restaurant in Berlin I am first time In Pakistani food and I never forget The food And also very nice Service friendly people I will adveic Just try Chicken vindhalo Laam tikka Frisch Salat etc.", user_id: 1)
